name: build-windows
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential mingw-w64 wget xxd make

      - name: Build exe, pass CC to all sub‑makes
        run: |
          set -e
          make CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ newflasher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: newflasher-win
          path: newflasher.exe
