name: build-windows
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW‑w64
        run: |
          choco install mingw -y
          echo "C:\Program Files\mingw-w64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build exe
        run: |
          make newflasher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: newflasher-win
          path: newflasher.exe
