name: build-windows
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential mingw-w64 wget xxd make

      - name: Pre‑download lib packages
        run: |
          set -e
          rm -f zlib-1.3.1.tar.gz
          wget -O zlib-1.3.1.tar.gz https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
          rm -f expat-2.2.9.tar.gz
          wget -O expat-2.2.9.tar.gz https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.gz

      - name: Build newflasher.exe
        run: |
          set -e
          make newflasher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: newflasher-win
          path: newflasher.exe
